### ISSUE TITLE
HOPE Primero Demo 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-demo#1]
## Background, context, and business value
OpenFn will demo syncing cases between Primero and a Postgres Database.

For example: As a Primero case worker, I want to refer a case for cash assistance, so that I can securely send beneficiary details to the cash assistance team.

## The specific request, in as few words as possible

See the data [flow diagrams](https://lucid.app/lucidchart/7af4115c-6544-46e0-bfb0-b137611f4494/edit?beaconFlowId=958A75EF0D4DF044&page=0_0#).
See the [mapping sheet](https://docs.google.com/spreadsheets/d/1yVZORyUOJ7z9zjqeWIkb4b2QtllMzqvJabe0luhq-KA/edit#gid=0) for field mappings and lookup tables.

Create Jobs 1 &2 in which OpenFn gets cases from Primero, and then maps and upserts data to the Postgres database. 
1. Get cases: `GET /api/v2/cases` -- where `last_updated_at` = today()
This should return: https://github.com/OpenFn/primero-demo/blob/main/sampleData/payload.json. Post to the inbox.
2. Map Primero response to Postgres using the mapping sheet linked above.
3. Upload data to Postgres.  

## state.json
I've added sample data here: https://github.com/OpenFn/primero-demo/blob/main/sampleData/payload.json
LP Credentials:
`Primero Play Demo Instance`
`OFG Demo Postgres DB`

## adaptor

Primero
Postgres

## trigger
Scheduled: Nightly @ 12:00 AM

## expression
Job 1: https://www.openfn.org/projects/p5ypvq/jobs/jy365a
Job 2: https://www.openfn.org/projects/p5ypvq/jobs/jyjp8e

**Comment by daissatou2** [comment]
@aleksa-krolls please add the credential for the database to be used. Please also add pipeline and move to backlog.

**Comment by aleksa-krolls** [comment]
@daissatou2 Added. 
1. Can you please provide **access to the mapping specs**? (Ideally always try to save things in a shared folder: https://drive.google.com/drive/folders/162itOWc1iRVTUdbgrpCyc9uWjS_p6wNI )
2. **What operation** would you like to perform in Postgres? An `upsert`? If yes, what is the unique id that can be used... in Primero is there a field that captures national ID or document number... or should we use `case_id`?
3. **Data flow** - what you had was accurate... but we want to be more detailed & precise. See the updated [data flow diagram](https://lucid.app/lucidchart/7af4115c-6544-46e0-bfb0-b137611f4494/edit?beaconFlowId=958A75EF0D4DF044&page=0_0#) and note how I added a `start event` for the timed sync, as well as a `gateway` to detail different scenarios. Let's review when we sync today. Fyi, I used this reference for inspiration: https://camunda.com/bpmn/reference/
4. Today can you **configure the jobs** in the test project and share with Taylor to link to?

**Comment by daissatou2** [comment]
1. Done  
2. Upsert on `case_id`. I've added this to the original issue. 
3. OK 
4. Job 1: https://www.openfn.org/projects/p5ypvq/jobs/jy365a, Job 2: https://www.openfn.org/projects/p5ypvq/jobs/jyjp8e

@taylordowns2000 this is ready for you.
